In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
from datetime import datetime
t1 = datetime(2009,10,20)

In [4]:
t1

datetime.datetime(2009, 10, 20, 0, 0)

In [7]:
date_list = [
    datetime(2016,9,1),
    datetime(2016,9,10),
    datetime(2017,9,1),
    datetime(2017,9,20),
    datetime(2017,10,1)
]

In [8]:
date_list

[datetime.datetime(2016, 9, 1, 0, 0),
 datetime.datetime(2016, 9, 10, 0, 0),
 datetime.datetime(2017, 9, 1, 0, 0),
 datetime.datetime(2017, 9, 20, 0, 0),
 datetime.datetime(2017, 10, 1, 0, 0)]

In [9]:
s1 = Series(np.random.rand(5),index=date_list)

In [10]:
s1

2016-09-01    0.190312
2016-09-10    0.833750
2017-09-01    0.296621
2017-09-20    0.766468
2017-10-01    0.861502
dtype: float64

In [11]:
s1.values

array([0.190312  , 0.83374979, 0.29662058, 0.76646768, 0.86150169])

In [12]:
s1.index

DatetimeIndex(['2016-09-01', '2016-09-10', '2017-09-01', '2017-09-20',
               '2017-10-01'],
              dtype='datetime64[ns]', freq=None)

In [13]:
s1[1]

0.8337497883527442

In [15]:
s1[datetime(2016,9,10)]

0.8337497883527442

In [16]:
s1['2016-9-10']

0.8337497883527442

In [17]:
s1['20160910']

0.8337497883527442

In [18]:
s1['2016-09']

2016-09-01    0.190312
2016-09-10    0.833750
dtype: float64

In [19]:
s1['2016']

2016-09-01    0.190312
2016-09-10    0.833750
dtype: float64

In [22]:
date_list_new = pd.date_range('2016-01-01',periods=100)

In [23]:
date_list_new

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
               '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
               '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
               '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
               '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
               '2016-01-29', '2016-01-30', '2016-01-31', '2016-02-01',
               '2016-02-02', '2016-02-03', '2016-02-04', '2016-02-05',
               '2016-02-06', '2016-02-07', '2016-02-08', '2016-02-09',
               '2016-02-10', '2016-02-11', '2016-02-12', '2016-02-13',
               '2016-02-14', '2016-02-15', '2016-02-16', '2016-02-17',
               '2016-02-18', '2016-02-19', '2016-02-20', '2016-02-21',
               '2016-02-22', '2016-02-23', '2016-02-24', '2016-02-25',
               '2016-02-26', '2016-02-27', '2016-02-28', '2016-02-29',
               '2016-03-01', '2016-03-02', '2016-03-03', '2016-03-04',
               '2016-03-05', '2016-03-06', '2016-03-07', '2016-03-08',
               '2016-03-09', '2016-03-10', '2016-03-11', '2016-03-12',
               '2016-03-13', '2016-03-14', '2016-03-15', '2016-03-16',
               '2016-03-17', '2016-03-18', '2016-03-19', '2016-03-20',
               '2016-03-21', '2016-03-22', '2016-03-23', '2016-03-24',
               '2016-03-25', '2016-03-26', '2016-03-27', '2016-03-28',
               '2016-03-29', '2016-03-30', '2016-03-31', '2016-04-01',
               '2016-04-02', '2016-04-03', '2016-04-04', '2016-04-05',
               '2016-04-06', '2016-04-07', '2016-04-08', '2016-04-09'],
              dtype='datetime64[ns]', freq='D')

In [24]:
date_list_new = pd.date_range('2016-01-01',periods=100,freq='W')

In [25]:
date_list_new

DatetimeIndex(['2016-01-03', '2016-01-10', '2016-01-17', '2016-01-24',
               '2016-01-31', '2016-02-07', '2016-02-14', '2016-02-21',
               '2016-02-28', '2016-03-06', '2016-03-13', '2016-03-20',
               '2016-03-27', '2016-04-03', '2016-04-10', '2016-04-17',
               '2016-04-24', '2016-05-01', '2016-05-08', '2016-05-15',
               '2016-05-22', '2016-05-29', '2016-06-05', '2016-06-12',
               '2016-06-19', '2016-06-26', '2016-07-03', '2016-07-10',
               '2016-07-17', '2016-07-24', '2016-07-31', '2016-08-07',
               '2016-08-14', '2016-08-21', '2016-08-28', '2016-09-04',
               '2016-09-11', '2016-09-18', '2016-09-25', '2016-10-02',
               '2016-10-09', '2016-10-16', '2016-10-23', '2016-10-30',
               '2016-11-06', '2016-11-13', '2016-11-20', '2016-11-27',
               '2016-12-04', '2016-12-11', '2016-12-18', '2016-12-25',
               '2017-01-01', '2017-01-08', '2017-01-15', '2017-01-22',
               '2017-01-29', '2017-02-05', '2017-02-12', '2017-02-19',
               '2017-02-26', '2017-03-05', '2017-03-12', '2017-03-19',
               '2017-03-26', '2017-04-02', '2017-04-09', '2017-04-16',
               '2017-04-23', '2017-04-30', '2017-05-07', '2017-05-14',
               '2017-05-21', '2017-05-28', '2017-06-04', '2017-06-11',
               '2017-06-18', '2017-06-25', '2017-07-02', '2017-07-09',
               '2017-07-16', '2017-07-23', '2017-07-30', '2017-08-06',
               '2017-08-13', '2017-08-20', '2017-08-27', '2017-09-03',
               '2017-09-10', '2017-09-17', '2017-09-24', '2017-10-01',
               '2017-10-08', '2017-10-15', '2017-10-22', '2017-10-29',
               '2017-11-05', '2017-11-12', '2017-11-19', '2017-11-26'],
              dtype='datetime64[ns]', freq='W-SUN')

In [26]:
date_list_new = pd.date_range('2016-01-01',periods=100,freq='W-MON')

In [27]:
date_list_new

DatetimeIndex(['2016-01-04', '2016-01-11', '2016-01-18', '2016-01-25',
               '2016-02-01', '2016-02-08', '2016-02-15', '2016-02-22',
               '2016-02-29', '2016-03-07', '2016-03-14', '2016-03-21',
               '2016-03-28', '2016-04-04', '2016-04-11', '2016-04-18',
               '2016-04-25', '2016-05-02', '2016-05-09', '2016-05-16',
               '2016-05-23', '2016-05-30', '2016-06-06', '2016-06-13',
               '2016-06-20', '2016-06-27', '2016-07-04', '2016-07-11',
               '2016-07-18', '2016-07-25', '2016-08-01', '2016-08-08',
               '2016-08-15', '2016-08-22', '2016-08-29', '2016-09-05',
               '2016-09-12', '2016-09-19', '2016-09-26', '2016-10-03',
               '2016-10-10', '2016-10-17', '2016-10-24', '2016-10-31',
               '2016-11-07', '2016-11-14', '2016-11-21', '2016-11-28',
               '2016-12-05', '2016-12-12', '2016-12-19', '2016-12-26',
               '2017-01-02', '2017-01-09', '2017-01-16', '2017-01-23',
               '2017-01-30', '2017-02-06', '2017-02-13', '2017-02-20',
               '2017-02-27', '2017-03-06', '2017-03-13', '2017-03-20',
               '2017-03-27', '2017-04-03', '2017-04-10', '2017-04-17',
               '2017-04-24', '2017-05-01', '2017-05-08', '2017-05-15',
               '2017-05-22', '2017-05-29', '2017-06-05', '2017-06-12',
               '2017-06-19', '2017-06-26', '2017-07-03', '2017-07-10',
               '2017-07-17', '2017-07-24', '2017-07-31', '2017-08-07',
               '2017-08-14', '2017-08-21', '2017-08-28', '2017-09-04',
               '2017-09-11', '2017-09-18', '2017-09-25', '2017-10-02',
               '2017-10-09', '2017-10-16', '2017-10-23', '2017-10-30',
               '2017-11-06', '2017-11-13', '2017-11-20', '2017-11-27'],
              dtype='datetime64[ns]', freq='W-MON')

In [28]:
date_list_new = pd.date_range('2016-01-01',periods=100,freq='H')

In [29]:
date_list_new

DatetimeIndex(['2016-01-01 00:00:00', '2016-01-01 01:00:00',
               '2016-01-01 02:00:00', '2016-01-01 03:00:00',
               '2016-01-01 04:00:00', '2016-01-01 05:00:00',
               '2016-01-01 06:00:00', '2016-01-01 07:00:00',
               '2016-01-01 08:00:00', '2016-01-01 09:00:00',
               '2016-01-01 10:00:00', '2016-01-01 11:00:00',
               '2016-01-01 12:00:00', '2016-01-01 13:00:00',
               '2016-01-01 14:00:00', '2016-01-01 15:00:00',
               '2016-01-01 16:00:00', '2016-01-01 17:00:00',
               '2016-01-01 18:00:00', '2016-01-01 19:00:00',
               '2016-01-01 20:00:00', '2016-01-01 21:00:00',
               '2016-01-01 22:00:00', '2016-01-01 23:00:00',
               '2016-01-02 00:00:00', '2016-01-02 01:00:00',
               '2016-01-02 02:00:00', '2016-01-02 03:00:00',
               '2016-01-02 04:00:00', '2016-01-02 05:00:00',
               '2016-01-02 06:00:00', '2016-01-02 07:00:00',
               '2016-01-02 08:00:00', '2016-01-02 09:00:00',
               '2016-01-02 10:00:00', '2016-01-02 11:00:00',
               '2016-01-02 12:00:00', '2016-01-02 13:00:00',
               '2016-01-02 14:00:00', '2016-01-02 15:00:00',
               '2016-01-02 16:00:00', '2016-01-02 17:00:00',
               '2016-01-02 18:00:00', '2016-01-02 19:00:00',
               '2016-01-02 20:00:00', '2016-01-02 21:00:00',
               '2016-01-02 22:00:00', '2016-01-02 23:00:00',
               '2016-01-03 00:00:00', '2016-01-03 01:00:00',
               '2016-01-03 02:00:00', '2016-01-03 03:00:00',
               '2016-01-03 04:00:00', '2016-01-03 05:00:00',
               '2016-01-03 06:00:00', '2016-01-03 07:00:00',
               '2016-01-03 08:00:00', '2016-01-03 09:00:00',
               '2016-01-03 10:00:00', '2016-01-03 11:00:00',
               '2016-01-03 12:00:00', '2016-01-03 13:00:00',
               '2016-01-03 14:00:00', '2016-01-03 15:00:00',
               '2016-01-03 16:00:00', '2016-01-03 17:00:00',
               '2016-01-03 18:00:00', '2016-01-03 19:00:00',
               '2016-01-03 20:00:00', '2016-01-03 21:00:00',
               '2016-01-03 22:00:00', '2016-01-03 23:00:00',
               '2016-01-04 00:00:00', '2016-01-04 01:00:00',
               '2016-01-04 02:00:00', '2016-01-04 03:00:00',
               '2016-01-04 04:00:00', '2016-01-04 05:00:00',
               '2016-01-04 06:00:00', '2016-01-04 07:00:00',
               '2016-01-04 08:00:00', '2016-01-04 09:00:00',
               '2016-01-04 10:00:00', '2016-01-04 11:00:00',
               '2016-01-04 12:00:00', '2016-01-04 13:00:00',
               '2016-01-04 14:00:00', '2016-01-04 15:00:00',
               '2016-01-04 16:00:00', '2016-01-04 17:00:00',
               '2016-01-04 18:00:00', '2016-01-04 19:00:00',
               '2016-01-04 20:00:00', '2016-01-04 21:00:00',
               '2016-01-04 22:00:00', '2016-01-04 23:00:00',
               '2016-01-05 00:00:00', '2016-01-05 01:00:00',
               '2016-01-05 02:00:00', '2016-01-05 03:00:00'],
              dtype='datetime64[ns]', freq='H')

In [30]:
date_list_new = pd.date_range('2016-01-01',periods=100,freq='5H')

In [31]:
date_list_new

DatetimeIndex(['2016-01-01 00:00:00', '2016-01-01 05:00:00',
               '2016-01-01 10:00:00', '2016-01-01 15:00:00',
               '2016-01-01 20:00:00', '2016-01-02 01:00:00',
               '2016-01-02 06:00:00', '2016-01-02 11:00:00',
               '2016-01-02 16:00:00', '2016-01-02 21:00:00',
               '2016-01-03 02:00:00', '2016-01-03 07:00:00',
               '2016-01-03 12:00:00', '2016-01-03 17:00:00',
               '2016-01-03 22:00:00', '2016-01-04 03:00:00',
               '2016-01-04 08:00:00', '2016-01-04 13:00:00',
               '2016-01-04 18:00:00', '2016-01-04 23:00:00',
               '2016-01-05 04:00:00', '2016-01-05 09:00:00',
               '2016-01-05 14:00:00', '2016-01-05 19:00:00',
               '2016-01-06 00:00:00', '2016-01-06 05:00:00',
               '2016-01-06 10:00:00', '2016-01-06 15:00:00',
               '2016-01-06 20:00:00', '2016-01-07 01:00:00',
               '2016-01-07 06:00:00', '2016-01-07 11:00:00',
               '2016-01-07 16:00:00', '2016-01-07 21:00:00',
               '2016-01-08 02:00:00', '2016-01-08 07:00:00',
               '2016-01-08 12:00:00', '2016-01-08 17:00:00',
               '2016-01-08 22:00:00', '2016-01-09 03:00:00',
               '2016-01-09 08:00:00', '2016-01-09 13:00:00',
               '2016-01-09 18:00:00', '2016-01-09 23:00:00',
               '2016-01-10 04:00:00', '2016-01-10 09:00:00',
               '2016-01-10 14:00:00', '2016-01-10 19:00:00',
               '2016-01-11 00:00:00', '2016-01-11 05:00:00',
               '2016-01-11 10:00:00', '2016-01-11 15:00:00',
               '2016-01-11 20:00:00', '2016-01-12 01:00:00',
               '2016-01-12 06:00:00', '2016-01-12 11:00:00',
               '2016-01-12 16:00:00', '2016-01-12 21:00:00',
               '2016-01-13 02:00:00', '2016-01-13 07:00:00',
               '2016-01-13 12:00:00', '2016-01-13 17:00:00',
               '2016-01-13 22:00:00', '2016-01-14 03:00:00',
               '2016-01-14 08:00:00', '2016-01-14 13:00:00',
               '2016-01-14 18:00:00', '2016-01-14 23:00:00',
               '2016-01-15 04:00:00', '2016-01-15 09:00:00',
               '2016-01-15 14:00:00', '2016-01-15 19:00:00',
               '2016-01-16 00:00:00', '2016-01-16 05:00:00',
               '2016-01-16 10:00:00', '2016-01-16 15:00:00',
               '2016-01-16 20:00:00', '2016-01-17 01:00:00',
               '2016-01-17 06:00:00', '2016-01-17 11:00:00',
               '2016-01-17 16:00:00', '2016-01-17 21:00:00',
               '2016-01-18 02:00:00', '2016-01-18 07:00:00',
               '2016-01-18 12:00:00', '2016-01-18 17:00:00',
               '2016-01-18 22:00:00', '2016-01-19 03:00:00',
               '2016-01-19 08:00:00', '2016-01-19 13:00:00',
               '2016-01-19 18:00:00', '2016-01-19 23:00:00',
               '2016-01-20 04:00:00', '2016-01-20 09:00:00',
               '2016-01-20 14:00:00', '2016-01-20 19:00:00',
               '2016-01-21 00:00:00', '2016-01-21 05:00:00',
               '2016-01-21 10:00:00', '2016-01-21 15:00:00'],
              dtype='datetime64[ns]', freq='5H')

In [33]:
s2 = Series(np.random.rand(100),index=date_list_new)

In [34]:
s2

2016-01-01 00:00:00    0.816251
2016-01-01 05:00:00    0.042747
2016-01-01 10:00:00    0.177428
2016-01-01 15:00:00    0.358365
2016-01-01 20:00:00    0.311411
2016-01-02 01:00:00    0.691675
2016-01-02 06:00:00    0.549883
2016-01-02 11:00:00    0.166020
2016-01-02 16:00:00    0.382037
2016-01-02 21:00:00    0.935136
2016-01-03 02:00:00    0.469686
2016-01-03 07:00:00    0.737179
2016-01-03 12:00:00    0.139252
2016-01-03 17:00:00    0.731186
2016-01-03 22:00:00    0.259993
2016-01-04 03:00:00    0.691160
2016-01-04 08:00:00    0.453419
2016-01-04 13:00:00    0.030577
2016-01-04 18:00:00    0.532965
2016-01-04 23:00:00    0.605989
2016-01-05 04:00:00    0.396831
2016-01-05 09:00:00    0.781937
2016-01-05 14:00:00    0.615936
2016-01-05 19:00:00    0.408239
2016-01-06 00:00:00    0.263984
2016-01-06 05:00:00    0.527859
2016-01-06 10:00:00    0.721327
2016-01-06 15:00:00    0.254159
2016-01-06 20:00:00    0.732178
2016-01-07 01:00:00    0.149833
                         ...
2016-01-15 14:00:00    0.599445
2016-01-15 19:00:00    0.960765
2016-01-16 00:00:00    0.308379
2016-01-16 05:00:00    0.360619
2016-01-16 10:00:00    0.185270
2016-01-16 15:00:00    0.610838
2016-01-16 20:00:00    0.369089
2016-01-17 01:00:00    0.629372
2016-01-17 06:00:00    0.835032
2016-01-17 11:00:00    0.611377
2016-01-17 16:00:00    0.375975
2016-01-17 21:00:00    0.289517
2016-01-18 02:00:00    0.249161
2016-01-18 07:00:00    0.509646
2016-01-18 12:00:00    0.713836
2016-01-18 17:00:00    0.019286
2016-01-18 22:00:00    0.191777
2016-01-19 03:00:00    0.639122
2016-01-19 08:00:00    0.400761
2016-01-19 13:00:00    0.122314
2016-01-19 18:00:00    0.531210
2016-01-19 23:00:00    0.321515
2016-01-20 04:00:00    0.685685
2016-01-20 09:00:00    0.419533
2016-01-20 14:00:00    0.067101
2016-01-20 19:00:00    0.127253
2016-01-21 00:00:00    0.983856
2016-01-21 05:00:00    0.629038
2016-01-21 10:00:00    0.614833
2016-01-21 15:00:00    0.811646
Freq: 5H, Length: 100, dtype: float64